- name: Deploy Terraform
  hosts: localhost
  gather_facts: true
  connection: local
  vars_files:
    - ../vars/all.yml
    - ../vars/phish.yml
  vars: 
  - deploy: true
  tasks:
  - name: roles
    include_role:
      name: '{{ roleinputvar }}'
    loop:
      - digitalocean
      - azure
    loop_control:
      loop_var: roleinputvar
    tags: [ never, phish ]

- name: Refresh Inventory
  hosts: localhost
  tasks:
  - meta: refresh_inventory
  - name: Wait for system to become reachable again
    wait_for_connection:
        delay: 10
        timeout: 300
  tags: [ never, phish ]

- name: Install Roles
  gather_facts: True
  hosts: phish
  connection: ssh
  become: True
  vars_files:
    - ../vars/all.yml
    - ../vars/phish.yml
  vars:
    pip_install_packages:
      - name: docker
  roles:
    - { role: weareinteractive.users }
    - { role: os }
    - { role: geerlingguy.pip }
    - { role: geerlingguy.ntp }
    - { role: geerlingguy.security }
    - { role: geerlingguy.firewall }
    - { role: docker }
    - { role: viasite-ansible.zsh, zsh_shared: yes}
  tags: [ never, phish ]

- name: Install Containers
  gather_facts: True
  hosts: phish
  connection: ssh
  become: True
  vars_files:
    - ../vars/all.yml
    - ../vars/phish.yml
  roles:
    - { role: nginx-docker }
    - { role: gophish-docker }
    - { role: evilginx2-docker }
  tags: [ never, phish ]