---
- name: Destroy Terraform
  hosts: localhost
  gather_facts: true
  connection: local
  vars_files:
    - ../vars/all.yml
    - ../vars/phish.yml
  vars: 
  - deploy: false
  tasks:
  - name: roles
    include_role:
      name: '{{ roleinputvar }}'
    loop:
      - digitalocean
      - azure
    loop_control:
      loop_var: roleinputvar
    tags: [ never, phish ]